# Generated by Django 4.2.29 on 2026-04-01 20:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Depoimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(help_text='Destrua a reputação desta pessoa com carinho.')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('alvo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depoimentos_recebidos', to=settings.AUTH_USER_MODEL)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depoimentos_feitos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='fracasso',
            name='usuario',
        ),
        migrations.AlterUniqueTogether(
            name='reacao',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='reacao',
            name='fracasso',
        ),
        migrations.RemoveField(
            model_name='reacao',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Comentario',
        ),
        migrations.DeleteModel(
            name='Fracasso',
        ),
        migrations.DeleteModel(
            name='Reacao',
        ),
    ]
