# Generated by Django 4.2.29 on 2026-04-01 20:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mural', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(help_text='Escreva algo condescendente.')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Fracasso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Ex: Deletei o banco de produção', max_length=200)),
                ('descricao', models.TextField(help_text='Chore aqui. O espaço é seguro.')),
                ('nivel_vergonha', models.CharField(choices=[('LEVE', 'Leve'), ('MEDIO', 'Médio'), ('CRITICO', 'Crítico'), ('FUGA', 'Mudar de Nome e País')], default='MEDIO', max_length=10)),
                ('data_do_ocorrido', models.DateField()),
                ('aprendizado', models.TextField(default='Nada, vou errar de novo.')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fracassos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('LIKE', 'Gostei (Polegar)'), ('RISO', 'Rindo da desgraça'), ('FACEPALM', 'Mão na testa'), ('APOIO', 'Força, guerreiro'), ('SURPRESA', 'Como você fez isso?')], max_length=15)),
                ('fracasso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reacoes', to='mural.fracasso')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('fracasso', 'usuario')},
            },
        ),
        migrations.DeleteModel(
            name='Depoimento',
        ),
        migrations.AddField(
            model_name='comentario',
            name='fracasso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='mural.fracasso'),
        ),
    ]
